version: 0.0
os: linux
files:
  - source: /
  destination: /var/www/html/knowhow-elasticsearch
hooks:
  BeforeInstall:
    - location: scripts/npm-before-install.sh
      timeout: 1200
      runas: ec2-user
  AfterInstall:
    - location: scripts/npm-install.sh
      timeout: 300
      runas: ec2-user